[package]
name = "atelier-client"
version = "0.1.0"
edition = "2018"

[dependencies]
capnp = "0.13"
capnp-rpc = "0.13"
tokio = "0.2"
futures = { version = "0.3", default-features = false }
atelier-schema = { path = "../schema" }