[package]
name = "atelier-client"
version = "0.1.0"
edition = "2018"

[dependencies]
capnp = "0.10.0"
capnp-rpc = "0.10.0"
tokio = "0.1"
futures = "0.1"
atelier-schema = { path = "../schema" }
chrono = "0.4.7"
parity-tokio-ipc = { git = "https://github.com/NikVolf/parity-tokio-ipc", branch = "master" }